# Generated by Django 5.1.7 on 2025-03-15 16:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
        ('inventario', '0002_puntocontrolhaccp_historicalcategoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificacionAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('organizacion_emisora', models.CharField(max_length=200)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('obtenida', 'Obtenida'), ('renovacion', 'En Renovación'), ('vencida', 'Vencida')], max_length=20)),
                ('descripcion', models.TextField()),
                ('requisitos', models.JSONField()),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='sostenibilidad/certificaciones/')),
            ],
            options={
                'verbose_name': 'Certificación Ambiental',
                'verbose_name_plural': 'Certificaciones Ambientales',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('financiero', 'Financiero'), ('operacional', 'Operacional'), ('calidad', 'Calidad'), ('logistica', 'Logística'), ('ventas', 'Ventas')], max_length=20)),
                ('descripcion', models.TextField()),
                ('formula', models.TextField()),
                ('unidad', models.CharField(max_length=50)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Indicador de Desempeño',
                'verbose_name_plural': 'Indicadores de Desempeño',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSostenibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_registro', models.CharField(choices=[('energia', 'Consumo Energético'), ('agua', 'Consumo de Agua'), ('residuos', 'Generación de Residuos'), ('emisiones', 'Emisiones de CO2'), ('reciclaje', 'Material Reciclado')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='sostenibilidad/evidencias/')),
            ],
            options={
                'verbose_name': 'Registro de Sostenibilidad',
                'verbose_name_plural': 'Registros de Sostenibilidad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='informe',
            name='tipo',
            field=models.CharField(choices=[('ventas', 'Informe de Ventas'), ('inventario', 'Informe de Inventario'), ('clientes', 'Informe de Clientes'), ('proveedores', 'Informe de Proveedores'), ('prediccion', 'Predicción de Demanda'), ('tendencias', 'Análisis de Tendencias'), ('kpis', 'Indicadores de Desempeño')], max_length=20),
        ),
        migrations.CreateModel(
            name='ObjetivoSostenibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('energia', 'Reducción de Consumo Energético'), ('agua', 'Optimización de Consumo de Agua'), ('residuos', 'Reducción de Residuos'), ('emisiones', 'Reducción de Emisiones'), ('reciclaje', 'Aumento de Reciclaje')], max_length=20)),
                ('descripcion', models.TextField()),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_objetivo', models.DateField()),
                ('progreso_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acciones_planificadas', models.TextField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo de Sostenibilidad',
                'verbose_name_plural': 'Objetivos de Sostenibilidad',
                'ordering': ['fecha_objetivo'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('demanda_predicha', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('intervalo_confianza_bajo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('intervalo_confianza_alto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('factores_estacionales', models.JSONField()),
                ('variables_externas', models.JSONField(default=dict)),
                ('precision_modelo', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Predicción de Demanda',
                'verbose_name_plural': 'Predicciones de Demanda',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.indicadordesempeno')),
            ],
            options={
                'verbose_name': 'Registro de KPI',
                'verbose_name_plural': 'Registros de KPIs',
                'ordering': ['-fecha'],
                'unique_together': {('indicador', 'fecha')},
            },
        ),
    ]
