# Generated by Django 5.1.7 on 2025-03-15 16:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('furgon', 'Furgón Refrigerado'), ('camion', 'Camión Refrigerado'), ('van', 'Van Refrigerada')], max_length=20)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temperatura_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(10)])),
                ('temperatura_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(10)])),
                ('en_servicio', models.BooleanField(default=True)),
                ('ultima_revision', models.DateField()),
                ('proxima_revision', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='temperatura_empaque',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='firma_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='temperatura_entrega',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='RutaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20)),
                ('temperatura_promedio', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_fin', models.TimeField(null=True)),
                ('kilometraje_inicial', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kilometraje_final', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='ruta_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.rutaentrega'),
        ),
    ]
