# Generated by Django 5.1.7 on 2025-03-15 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10)),
                ('hora', models.TimeField()),
                ('ruta_destino', models.CharField(max_length=255)),
                ('mantener_versiones', models.PositiveIntegerField()),
                ('encriptacion_habilitada', models.BooleanField(default=True)),
                ('notificar_error', models.BooleanField(default=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('proximo_backup', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Backup',
                'verbose_name_plural': 'Configuraciones de Backup',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('induccion', 'Inducción'), ('seguridad', 'Seguridad'), ('calidad', 'Control de Calidad'), ('haccp', 'HACCP'), ('manipulacion', 'Manipulación de Alimentos'), ('tecnica', 'Capacitación Técnica')], max_length=20)),
                ('descripcion', models.TextField()),
                ('duracion_horas', models.PositiveIntegerField()),
                ('instructor', models.CharField(max_length=200)),
                ('material', models.FileField(blank=True, null=True, upload_to='capacitaciones/material/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('valor', models.JSONField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política de Seguridad',
                'verbose_name_plural': 'Políticas de Seguridad',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Contrato Indefinido'), ('plazo_fijo', 'Plazo Fijo'), ('temporal', 'Temporal')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certificado_manipulacion', models.FileField(blank=True, null=True, upload_to='empleados/certificados/')),
                ('fecha_vencimiento_certificado', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('reprobado', 'Reprobado')], default='pendiente', max_length=20)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='capacitaciones/certificados/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.capacitacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.empleado')),
            ],
            options={
                'verbose_name': 'Participación en Capacitación',
                'verbose_name_plural': 'Participaciones en Capacitaciones',
                'unique_together': {('empleado', 'capacitacion')},
            },
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='participantes',
            field=models.ManyToManyField(through='dashboard.ParticipacionCapacitacion', to='dashboard.empleado'),
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('login', 'Iniciar Sesión'), ('logout', 'Cerrar Sesión'), ('error', 'Error')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('detalles', models.JSONField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('area_trabajo', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='dashboard.empleado')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_supervisados', to='dashboard.empleado')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('backup_codes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP de Usuario',
                'verbose_name_plural': 'OTPs de Usuarios',
            },
        ),
    ]
